platform:
  type: "napcat" # 消息平台，兼容 napcat, llonebot, lagrange
  http_host: "127.0.0.1" # HTTP 服务器 IP，非 docker 部署一般为 127.0.0.1，docker 部署一般为宿主机局域网 IP
  http_port: 2333 # HTTP 服务器端口，通常为 2333 或 3000
  api_token: "" # HTTP 服务器 token，没有则不填

api:
  video_api:
    # - url: "https://dayu.qqsuu.cn/moyuribaoshipin/apis.php?type=json"
    #   pipeline: "fetch | data | direct_url"

    - url: "https://v2.api-m.com/api/meinv?return=302"
      pipeline: "direct_url"

    # - url: "https://onexiaolaji.cn/RandomPicture/api/api-video.php"
    #   pipeline: "fetch | raw_url | download_url"

    - url: "https://tucdn.wpon.cn/api-girl/index.php"
      pipeline: "direct_url"

    - url: "http://api.yujn.cn/api/zzxjj.php?type=video"
      pipeline: "direct_url"

  picture_api:
    - url: "https://api.zhcnli.cn/api/sjtp/tupian.php?type=hs"
      pipeline: "direct_url"

download:
  cache_folder: "/app/sharedFolder"
